[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Path         /opt/monitoring/fluent-bit/logs/go-monitor-demo.log
    Tag          go.demo
    DB           /opt/monitoring/fluent-bit/state/tail.db
    Refresh_Interval 2
    Read_from_Head true
[INPUT]
    Name         tail
    Path         /opt/monitoring/fluent-bit/logs/gateway/*.log
    Tag          gateway
    DB           /opt/monitoring/fluent-bit/state/gateway-tail.db
    Refresh_Interval 2
    Read_from_Head true

[INPUT]
    Name         tail
    Path         /opt/monitoring/fluent-bit/logs/worker/*.log
    Tag          worker
    DB           /opt/monitoring/fluent-bit/state/worker-tail.db
    Refresh_Interval 2
    Read_from_Head true

[OUTPUT]
    Name         loki
    Match        go.demo
    Host         127.0.0.1
    Port         3100
    Labels       job=go-monitor-demo,source=fluent-bit
    Line_Format  json
[OUTPUT]
    Name         loki
    Match        gateway
    Host         127.0.0.1
    Port         3100
    Labels       job=go-gateway-demo,service=gateway,source=fluent-bit
    Line_Format  json

[OUTPUT]
    Name         loki
    Match        worker
    Host         127.0.0.1
    Port         3100
    Labels       job=go-worker-demo,service=worker,source=fluent-bit
    Line_Format  json
